Add commit-msg hook to check commit message format (no past tense allowed)

diff --git a/_infrastructure/install-hooks b/_infrastructure/install-hooks
--- a/_infrastructure/install-hooks
+++ b/_infrastructure/install-hooks
@@ -1,10 +1,15 @@
-cp pre-commit ../.git/hooks/ && cp pre-push ../.git/hooks/;
+#!/bin/bash
 
-# Check last return code (#?).
-if [ $? == 1 ]
-then
-	echo "Something went wrong."
-	exit 1
-fi
+declare -a hooks=("commit-msg" "pre-commit" "pre-push")
 
-echo "Done. Installed pre-commit and pre-push hooks."
+for hook in "${hooks[@]}"
+do
+    cp $hook ../.git/hooks/
+
+    if [ $? == 1 ]; then
+        printf "Something went wrong. Failed to install $hook hook\n"
+        exit 1
+    else
+        printf "Installed $hook hook.\n"
+    fi
+done
diff --git a/_infrastructure/pre-commit b/_infrastructure/pre-commit
--- a/_infrastructure/pre-commit
+++ b/_infrastructure/pre-commit
@@ -2,28 +2,33 @@
 
 ### RUN PHP CODE SNIFFER AND ABORT ON ANY WARNING OR ERROR
 
-printf "Running phpcs...\n"
+NOCOLOR='\033[0m'
+YELLOW='\033[0;33m'
+RED='\033[0;31m'
+
+printf "${YELLOW}Running phpcs...${NOCOLOR}\n"
+
 FILES_PHP=$(git diff --name-only --cached --relative | grep '\.php\?$')
 if [ "$FILES_PHP" != "" ]; then
     for FILE in $FILES_PHP
     do
-      OUTPUT=`phpcs --standard=ci/ruleset.xml $FILE`
-      if [ $? -ne 0 ]
-      then
-      	printf "[PHP] Code style verification failed. Aborting Commit!\n"
-      	printf "$OUTPUT\n"
-      	exit 1
-      fi
+        OUTPUT=`phpcs --standard=ci/ruleset.xml $FILE`
+        if [ $? -ne 0 ]
+        then
+            printf "Code style verification in $FILE failed. Aborting Commit!\n"
+            printf "$OUTPUT\n"
+            exit 1
+        fi
     done
 fi
 
-printf "Running standard...\n"
+### RUN STANDARD
+
+printf "${YELLOW}Running standard...${NOCOLOR}\n"
 OUTPUT=`git diff --name-only --cached --relative | grep '\.jsx\?$' | xargs standard`
 if [ $? -ne 0 ]
 then
-	printf "[JS] Code style verification failed. Aborting Commit!\n"
-	printf "$OUTPUT\n"
-	exit 1
+    printf "[JS] Code style verification failed. Aborting Commit!\n"
+    printf "$OUTPUT\n"
+    exit 1
 fi
-
-exit 0
