Don't check deleted files in pre-commit hook

diff --git a/_infrastructure/pre-commit b/_infrastructure/pre-commit
--- a/_infrastructure/pre-commit
+++ b/_infrastructure/pre-commit
@@ -10,16 +10,21 @@ printf "${YELLOW}Running phpcs...${NOCOLOR}\n"
 
 FILES_PHP=$(git diff --name-only --cached --relative | grep '\.php\?$')
 if [ "$FILES_PHP" != "" ]; then
-    for FILE in $FILES_PHP
-    do
-        OUTPUT=`phpcs --standard=ci/ruleset.xml $FILE`
-        if [ $? -ne 0 ]
-        then
-            printf "Code style verification in $FILE failed. Aborting Commit!\n"
-            printf "$OUTPUT\n"
-            exit 1
-        fi
-    done
+  for FILE in $FILES_PHP
+  do
+
+    # File has been removed.
+    if [ ! -f "$FILE" ]; then
+      continue;
+    fi
+
+    OUTPUT=`phpcs --standard=ci/ruleset.xml $FILE`
+    if [ $? -ne 0 ]; then
+      printf "Code style verification in $FILE failed. Aborting Commit!\n"
+      printf "$OUTPUT\n"
+      exit 1
+    fi
+  done
 fi
 
 ### RUN STANDARD
@@ -28,7 +33,7 @@ printf "${YELLOW}Running standard...${NOCOLOR}\n"
 OUTPUT=`git diff --name-only --cached --relative | grep '\.jsx\?$' | xargs standard`
 if [ $? -ne 0 ]
 then
-    printf "[JS] Code style verification failed. Aborting Commit!\n"
-    printf "$OUTPUT\n"
-    exit 1
+  printf "[JS] Code style verification failed. Aborting Commit!\n"
+  printf "$OUTPUT\n"
+  exit 1
 fi
